apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: node-app
spec:
  generators:
    - list:
        elements:
          - env: dev
            url: https://kubernetes.default.svc
          - env: preprod
            url: https://kubernetes.default.svc
          - env: prod
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'node-app-{{env}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/Asanio06/gitops-config
        targetRevision: HEAD
        path: config
        plugin:
          name: argocd-vault-plugin-helm
          env:
            - name: helm_args
              value: |
                -f values.{{env}}.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: node-app
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Replace=true
        automated:
          selfHeal: true
          prune: true
