app:
  env: dev
  replicas: 1
  image:
    tags: asanio06/examplenode:57545aa63351b4f86cc700a7924794ed0b3eece4
    pull: Always
  deployment:
    container:
      port: 3000
  service:
    port: 3000
