app:
  env: preprod
  replicas: 2
  image:
    tags: asanio06/examplenode:46c7aaaa66f66a8c8dde2a5920d656095981ebbd
    pull: Always
  deployment:
    container:
      port: 3000
  service:
    port: 3200
