app:
  env: dev
  replicas: 1
  image:
    tags: asanio06/examplenode:bf94e9e34a51e3485967b23796ded767b0ad25b5
    pull: Always
  deployment:
    container:
      port: 3000
  service:
    port: 3000
