apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-{{  .Values.app.env  }}
spec:
  selector:
    matchLabels:
      app: node-app-{{  .Values.app.env  }}
  replicas: {{  .Values.app.replicas  }}
  template:
    metadata:
      labels:
        app: node-app-{{ .Values.app.env }}
    spec:
      containers:
        - name: node-app
          image: {{ .Values.app.image.tags }}
          env:
            - name: MY_TEST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret-{{  .Values.app.env  }}
                  key: test-password
                  optional: false
          ports:
            - containerPort: {{ .Values.app.deployment.container.port  }}

