apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-node-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /dev
            pathType: Prefix
            backend:
              service:
                name: node-app-dev-service
                port:
                  number: 80
          - path: /preprod
            pathType: Prefix
            backend:
              service:
                name: node-app-preprod-service
                port:
                  number: 80