apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-node-app-{{  .Values.app.env  }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /{{  .Values.app.env  }}
            pathType: Prefix
            backend:
              service:
                name: node-app-{{  .Values.app.env  }}-service
                port:
                  number: {{  .Values.app.service.port  }}