apiVersion: v1
kind: Secret
metadata:
  name: my-secret-{{  .Values.app.env  }}
  annotations:
    avp.kubernetes.io/kv-version: '2'
    avp.kubernetes.io/path: "secret/data/argocd/{{  .Values.app.env  }}/my-secret-test"

data:
  test-password: <test-password | base64encode>