apiVersion: v1
kind: Secret
metadata:
  name: my-secret-{{  .Values.app.env  }}
  annotations:
    avp.kubernetes.io/path: "secret/{{  .Values.app.env  }}/my-secret-test"
type: Opaque
stringData:
  test-password: <test-password>