apiVersion: v1
kind: Service
metadata:
  name: node-app-{{  .Values.app.env  }}-service
spec:
  type: ClusterIP
  selector:
    app: node-app-{{  .Values.app.env  }}
  ports:
  - port: {{  .Values.app.service.port  }}
    protocol: TCP
    targetPort: {{  .Values.app.deployment.container.port }}
  
