name: Repository Dispatch

on:
  repository_dispatch:
    types: [update-kube-config]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Is release
      run: | 
        echo "${{ github.event.client_payload.release }}"
        echo "${{ github.event.client_payload.branch }}"
        

    - name: Deploy on production
      uses: mikefarah/yq@master
      if: ${{ github.event.client_payload.release }}
      with:
        cmd: yq eval '.app.image.tags= "${{ github.event.client_payload.image }}"' -i config/values.prod.yaml

    - name: Deploy on preprod
      uses: mikefarah/yq@master
      if: ${{ github.event.client_payload.branch == 'main' }}
      with:
        cmd: yq eval '.app.image.tags= "${{ github.event.client_payload.image }}"' -i config/values.preprod.yaml

    - name: Deploy on test
      uses: mikefarah/yq@master
      if: ${{ github.event.client_payload.branch == 'develop' }}
      with:
        cmd: yq eval '.app.image.tags= "${{ github.event.client_payload.image }}"' -i config/values.dev.yaml



    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes