name: Repository Dispatch

on:
  repository_dispatch:
    types: [update-kube-config]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Is release
      run: | 
        echo "${{ github.event.client_payload.release }}"
        

    - name: Update Image Version
      id: imgupd
      uses: mikefarah/yq@master
      with:
        cmd: yq eval '.spec.template.spec.containers[0].image = "${{ github.event.client_payload.image }}"' -i node-app/deployment.yaml
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply image name changes